export const SET_LOADING = "SET_LOADING";

// shows
export const FETCH_SHOWS_DATA = "FETCH_SHOWS_DATA";
export const SET_GENRES_LISTS = "SET_GENRES_LISTS";
export const SET_SHOW_DETAILS = "SET_SHOW_DETAILS";
export const SEARCH_MATCHING_SHOWS = "SEARCH_MATCHING_SHOWS";
export const CLEAR_SHOW_DETAILS = "CLEAR_SHOW_DETAILS";

// alerts
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
